apiVersion: apps/v1
kind: Deployment
metadata:
  name: augury-deployment
  namespace: staging
  labels:
    app: augury-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: augury
  template:
    metadata:
      labels:
        app: augury
    spec:
      containers:
      - name: application
        image: ghcr.io/ozlevka/augury-test:309d152277d49f2ee95df42d5b1570d12c7b82a9-65
        ports:
        - containerPort: 8080